export const TP_PARAMETROS = {
  TP_REGISTRO: 1,
  TP_RETORNA_A: 3,
  TP_PREGUNTA: 6,
  TP_CONTENIDO: 4,
  TP_CONDICION: 7,
  TP_CEREBRO: 11,
  TP_ENERGIA: 12,
  TP_CAUSA: 13,
  TP_ENERGIA_CAT: 15,
  TP_CAT_ENERGIA: 15,
  TP_PARTES_CUERPO: [17,
    18,
    19,
    20,
    21,
    22
  ],
  TP_SENSACION: 23,
  TP_SENSACION_COMO: 24,
  TP_ESTRES:25

};
